In [1]:
import pandas as pd
import tensorflow as tf

# 레모네이드 수요 예측

In [6]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
레모네이드 = pd.read_csv(파일경로)
레모네이드.head()

온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48

In [7]:
독립 = 레모네이드[['온도']]
종속 = 레모네이드[['판매량']]

In [8]:
독립.shape, 종속.shape

((6, 1), (6, 1))

뉴런 하나로 만들어진 모델

In [9]:


X = tf.keras.layers.Input(shape=[1]) #독립변수가 온도 하나이기 때문에 shape =[1]
Y = tf.keras.layers.Dense(1)(X) #알고싶은 종속변수도 1이라 dense도 1로 설정
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [13]:
model.fit(독립, 종속, epochs=10000, verbose=0)

In [15]:
model.fit(독립, 종속, epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 11ms/step - loss: 1.4304e-04
Epoch 2/10
1/1 [==============================] - 0s 9ms/step - loss: 1.4304e-04
Epoch 3/10
1/1 [==============================] - 0s 7ms/step - loss: 1.4307e-04
Epoch 4/10
1/1 [==============================] - 0s 17ms/step - loss: 1.4314e-04
Epoch 5/10
1/1 [==============================] - 0s 8ms/step - loss: 1.4324e-04
Epoch 6/10
1/1 [==============================] - 0s 9ms/step - loss: 1.4326e-04
Epoch 7/10
1/1 [==============================] - 0s 5ms/step - loss: 1.4321e-04
Epoch 8/10
1/1 [==============================] - 0s 5ms/step - loss: 1.4322e-04
Epoch 9/10
1/1 [==============================] - 0s 9ms/step - loss: 1.4325e-04
Epoch 10/10
1/1 [==============================] - 0s 5ms/step - loss: 1.4322e-04


In [14]:
print(model.predict([[15]]))

[[30.00133]]


# 보스턴 집값 예측

In [16]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
print(보스턴.columns)

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


In [17]:
보스턴.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [18]:
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]

In [19]:
X = tf.keras.layers.Input(shape=[13])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [20]:
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 26.5330
Epoch 2/10
16/16 [==============================] - 0s 3ms/step - loss: 26.7144
Epoch 3/10
16/16 [==============================] - 0s 4ms/step - loss: 26.3536
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 26.9430
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 26.7698
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 26.5027
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 26.6325
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 26.4319
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 26.1485
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 26.2676


In [21]:
print(model.predict(독립[5:10]))

[[25.93752 ]
 [20.61021 ]
 [17.494316]
 [ 8.846531]
 [17.122433]]


In [22]:
print(model.get_weights())

[array([[-0.08894066],
       [ 0.07484993],
       [-0.05707277],
       [ 3.3533297 ],
       [ 1.4264114 ],
       [ 3.8948615 ],
       [ 0.01823574],
       [-0.89260674],
       [ 0.14624642],
       [-0.01011491],
       [ 0.04819113],
       [ 0.01568404],
       [-0.5869491 ]], dtype=float32), array([2.4902687], dtype=float32)]


# 아이리스 품종 분류

In [2]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

이전의 데이터들은 종속변수가 수치형이었으나, 아이리스품종분류의 경우에는 범주형 자료인 것이 다르다.

In [3]:
아이리스 = pd.get_dummies(아이리스)

In [4]:
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [7]:
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]

In [5]:
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [8]:
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1577 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1580 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1580 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 10ms/step - loss: 0.1577 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1572 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1576 - accuracy: 0.9733
Epoch 7/10
5/5 [==============================] - 0s 5ms/step - loss: 0.1574 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1570 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1566 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1570 - accuracy: 0.9800


In [9]:
print(model.predict(독립[:5]))
print(종속[:5])

[[9.9896061e-01 1.0392128e-03 7.8765630e-08]
 [9.9591571e-01 4.0837387e-03 5.5025225e-07]
 [9.9810106e-01 1.8987278e-03 2.5651079e-07]
 [9.9538714e-01 4.6116677e-03 1.1722318e-06]
 [9.9917752e-01 8.2229095e-04 6.9348580e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


# 히든레이어

In [10]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)

In [11]:
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]

In [12]:
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(5, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [14]:
model.fit(독립, 종속, epochs=1000,verbose=0)

In [15]:
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 24.0479
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 23.3931
Epoch 3/10
16/16 [==============================] - 0s 3ms/step - loss: 23.8489
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 24.2264
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 24.4172
Epoch 6/10
16/16 [==============================] - 0s 3ms/step - loss: 24.5481
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 22.6625
Epoch 8/10
16/16 [==============================] - 0s 3ms/step - loss: 24.0835
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 22.2857
Epoch 10/10
16/16 [==============================] - 0s 3ms/step - loss: 23.8646


In [16]:
print(model.predict(독립[:5]))
print(종속[:5])

[[32.55609 ]
 [25.447836]
 [32.397743]
 [31.786886]
 [30.31867 ]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [17]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________
